= Impressum
:published_at: 2015-01-01

*Lukas Wöhrl* +
Schlangenweg 4 +
34117 Kassel

E-Mail: lukas@woehrl.net

Inhaltlich Verantwortlicher gemäß § 55 Abs. 2 RStV: Lukas Wöhrl

==== Rechtliche Hinweise
Inhalt und Gestaltung der Internet-Seiten sind urheberrechtlich geschützt. Eine Vervielfältigung der Seiten oder ihrer Inhalte bedarf der vorherigen schriftlichen Zustimmung von Lukas Wöhrl. Die auf den Webseiten genannten Marken und Firmen sind gesetzlich geschützte Warenzeichen.

==== Gewährleistung
Lukas Wöhrl prüft und aktualisiert die Informationen auf seinen Webseiten laufend. Trotz aller Sorgfalt können sich Angaben und die ihnen zugrunde liegenden Sachverhalte im Laufe der Zeit verändert haben. Eine Haftung oder Garantie für die Aktualität, Richtigkeit und Vollständigkeit der zur Verfügung gestellten Informationen können wir daher nicht übernehmen.

Gleiches gilt für alle weiteren Webseiten, auf die mittels Link verwiesen wird. Die Verantwortung für Inhalt und Gestaltung dieser Seiten liegt beim jeweiligen Anbieter.
Wenn Sie weitere Fragen zur Nutzung unseres Internet-Angebotes oder zur Verwendung Ihrer persönlichen Daten haben, stehen wir Ihnen für Auskünfte gerne zur Verfügung.